# Generated by Django 4.0.5 on 2022-06-12 08:15

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
